return {
	mod_title = {
		en = "\238\128\169 {#color(196,50,30)}Mechanicus Power Sword{#reset()}: Machine Spirit Upgrade",
	},
	mod_description = {
		en = "Charge readouts for the Mechanicus Power Sword and other charge weapons: a 4/6 counter with optional recharge underline and recovery countdown, and a bar for the special's wind-up stages or the recharge tick. All off by default. Movable with Custom HUD or the offsets here.",
		ru = "Индикация зарядов для силового меча Механикус и другого зарядного оружия: счётчик 4/6 с подчёркиванием перезарядки и отсчётом восстановления, плюс полоса стадий замаха спецатаки или тика перезарядки. По умолчанию всё выключено. Двигается через Custom HUD или смещениями здесь.",
		["zh-cn"] = "为机械教动力剑及其他充能武器提供充能读数：4/6 计数器（可选回充下划线与恢复倒计时），以及显示特殊攻击蓄力阶段或回充计时的进度条。默认全部关闭。可用 Custom HUD 拖动，或使用此处的偏移设置。",
		["zh-tw"] = "為機械教動力劍及其他充能武器提供充能讀數：4/6 計數器（可選回充底線與恢復倒數），以及顯示特殊攻擊蓄力階段或回充計時的進度條。預設全部關閉。可用 Custom HUD 拖曳，或使用此處的偏移設定。",
		ja = "メカニカス・パワーソードなどチャージ武器のチャージ表示：4/6 カウンター（リチャージ下線と回復カウントダウンはお好みで）、特殊攻撃の溜め段階またはリチャージを示すバー。初期状態ではすべてオフ。Custom HUD かここのオフセットで移動可能。",
	},

	numbers_group = {
		en = "Charge numbers",
		ru = "Числа зарядов",
		["zh-cn"] = "充能数字",
		["zh-tw"] = "充能數字",
		ja = "チャージ数",
	},
	bar_group = {
		en = "Charge bar",
		ru = "Полоса зарядов",
		["zh-cn"] = "充能条",
		["zh-tw"] = "充能條",
		ja = "チャージバー",
	},
	shared_group = {
		en = "General",
		ru = "Общее",
		["zh-cn"] = "通用",
		["zh-tw"] = "通用",
		ja = "全般",
	},

	numbers_enabled = {
		en = "Show the numbers",
		ru = "Показывать числа",
		["zh-cn"] = "显示数字",
		["zh-tw"] = "顯示數字",
		ja = "数字を表示",
	},
	numbers_enabled_description = {
		en = "The charge readout, e.g. 4/6.",
		ru = "Счётчик зарядов, например 4/6.",
		["zh-cn"] = "充能读数，例如 4/6。",
		["zh-tw"] = "充能讀數，例如 4/6。",
		ja = "チャージの読み出し。例：4/6。",
	},

	number_format = {
		en = "Readout",
		ru = "Формат",
		["zh-cn"] = "读数格式",
		["zh-tw"] = "讀數格式",
		ja = "表示形式",
	},
	number_format_description = {
		en = "Charges, or special uses (charges divided by the cost per empowered hit -- 4/8 on the Arc Maul; same as charges on cost-1 weapons).",
		ru = "Заряды или применения спецатаки (заряды, делённые на цену усиленного удара -- 4/8 у дуговой булавы; на оружии с ценой 1 совпадает с зарядами).",
		["zh-cn"] = "充能数，或特殊攻击使用次数（充能除以每次强化命中的消耗 -- 电弧锤为 4/8；消耗为 1 的武器与充能数相同）。",
		["zh-tw"] = "充能數，或特殊攻擊使用次數（充能除以每次強化命中的消耗 -- 電弧鎚為 4/8；消耗為 1 的武器與充能數相同）。",
		ja = "チャージ数、または特殊攻撃の使用回数（チャージ数を強化ヒット1回のコストで割った値 -- アークモールは 4/8。コスト1の武器ではチャージ数と同じ）。",
	},
	number_format_current_max = {
		en = "Charges (4/6)",
		ru = "Заряды (4/6)",
		["zh-cn"] = "充能（4/6）",
		["zh-tw"] = "充能（4/6）",
		ja = "チャージ（4/6）",
	},
	number_format_current = {
		en = "Charges (4)",
		ru = "Заряды (4)",
		["zh-cn"] = "充能（4）",
		["zh-tw"] = "充能（4）",
		ja = "チャージ（4）",
	},
	number_format_uses_max = {
		en = "Special uses (4/8)",
		ru = "Применения (4/8)",
		["zh-cn"] = "使用次数（4/8）",
		["zh-tw"] = "使用次數（4/8）",
		ja = "使用回数（4/8）",
	},
	number_format_uses = {
		en = "Special uses (4)",
		ru = "Применения (4)",
		["zh-cn"] = "使用次数（4）",
		["zh-tw"] = "使用次數（4）",
		ja = "使用回数（4）",
	},

	font_size = {
		en = "Font size",
		ru = "Размер шрифта",
		["zh-cn"] = "字号",
		["zh-tw"] = "字型大小",
		ja = "フォントサイズ",
	},
	font_size_description = {
		en = "1080p reference pixels.",
		ru = "Пиксели при 1080p.",
		["zh-cn"] = "以 1080p 为基准的像素。",
		["zh-tw"] = "以 1080p 為基準的像素。",
		ja = "1080p 基準のピクセル。",
	},

	opacity = {
		en = "Opacity",
		ru = "Непрозрачность",
		["zh-cn"] = "不透明度",
		["zh-tw"] = "不透明度",
		ja = "不透明度",
	},
	opacity_description = {
		en = "0-255. Also the underline's fill.",
		ru = "0-255. Также заливка подчёркивания.",
		["zh-cn"] = "0-255。也是下划线的填充。",
		["zh-tw"] = "0-255。也是底線的填滿。",
		ja = "0-255。下線の塗りにも適用。",
	},

	numbers_offset_x = {
		en = "Offset X",
		ru = "Смещение X",
		["zh-cn"] = "X 偏移",
		["zh-tw"] = "X 偏移",
		ja = "オフセット X",
	},
	numbers_offset_x_description = {
		en = "Positive is right. Custom HUD users: drag the element instead.",
		ru = "Положительное -- вправо. С Custom HUD лучше перетащить элемент.",
		["zh-cn"] = "正值向右。Custom HUD 用户：请直接拖动元素。",
		["zh-tw"] = "正值向右。Custom HUD 使用者：請直接拖曳元件。",
		ja = "正の値で右へ。Custom HUD 使用時は要素をドラッグ推奨。",
	},
	numbers_offset_y = {
		en = "Offset Y",
		ru = "Смещение Y",
		["zh-cn"] = "Y 偏移",
		["zh-tw"] = "Y 偏移",
		ja = "オフセット Y",
	},
	numbers_offset_y_description = {
		en = "Positive is down.",
		ru = "Положительное -- вниз.",
		["zh-cn"] = "正值向下。",
		["zh-tw"] = "正值向下。",
		ja = "正の値で下へ。",
	},

	underline_enabled = {
		en = "Recharge underline",
		ru = "Подчёркивание перезарядки",
		["zh-cn"] = "回充下划线",
		["zh-tw"] = "回充底線",
		ja = "リチャージ下線",
	},
	underline_enabled_description = {
		en = "Thin line by the readout, fills toward the next special use. Hidden at full. Fill follows the readout colour, background the bar's background colour.",
		ru = "Тонкая линия у счётчика, заполняется к следующему применению. Скрыта при полном запасе. Заливка -- цвета счётчика, фон -- цвета фона полосы.",
		["zh-cn"] = "紧贴读数的细线，随下一次特殊使用的恢复而填充。充能满时隐藏。填充色跟随读数颜色，背景用进度条的背景色。",
		["zh-tw"] = "緊貼讀數的細線，隨下一次特殊使用的恢復而填滿。充能滿時隱藏。填滿色跟隨讀數顏色，背景用進度條的背景色。",
		ja = "数字のそばの細い線が次の特殊使用に向けて満ちる。満タン時は非表示。塗りは数字の色、背景はバーの背景色に従う。",
	},

	underline_position = {
		en = "Position",
		ru = "Положение",
		["zh-cn"] = "位置",
		["zh-tw"] = "位置",
		ja = "位置",
	},
	underline_position_description = {
		en = "Which side of the readout.",
		ru = "С какой стороны счётчика.",
		["zh-cn"] = "位于读数的哪一侧。",
		["zh-tw"] = "位於讀數的哪一側。",
		ja = "数字のどちら側か。",
	},
	underline_position_below = {
		en = "Below",
		ru = "Снизу",
		["zh-cn"] = "下方",
		["zh-tw"] = "下方",
		ja = "下",
	},
	underline_position_above = {
		en = "Above",
		ru = "Сверху",
		["zh-cn"] = "上方",
		["zh-tw"] = "上方",
		ja = "上",
	},

	hint_countdown = {
		en = "Recovery countdown",
		ru = "Отсчёт восстановления",
		["zh-cn"] = "恢复倒计时",
		["zh-tw"] = "恢復倒數",
		ja = "回復カウントダウン",
	},
	hint_countdown_description = {
		en = "Seconds to the next charge after a special swing. Only during that delay -- never for the ordinary tick, never on the Arc Maul. Needs the numbers.",
		ru = "Секунды до следующего заряда после спецудара. Только во время этой задержки -- не для обычного тика и не на дуговой булаве. Требует включённых чисел.",
		["zh-cn"] = "特殊挥击后距下一充能的秒数。仅在该延迟期间显示 -- 普通回充不显示，电弧锤不显示。需要开启数字。",
		["zh-tw"] = "特殊揮擊後距下一充能的秒數。僅在該延遲期間顯示 -- 普通回充不顯示，電弧鎚不顯示。需要開啟數字。",
		ja = "特殊攻撃の後、次のチャージまでの秒数。その遅延中のみ表示 -- 通常のリチャージやアークモールでは出ない。数字の表示が必要。",
	},

	countdown_font_size = {
		en = "Countdown: font size",
		ru = "Отсчёт: размер шрифта",
		["zh-cn"] = "倒计时：字号",
		["zh-tw"] = "倒數：字型大小",
		ja = "カウントダウン：フォントサイズ",
	},
	countdown_font_size_description = {
		en = "1080p reference pixels.",
		ru = "Пиксели при 1080p.",
		["zh-cn"] = "以 1080p 为基准的像素。",
		["zh-tw"] = "以 1080p 為基準的像素。",
		ja = "1080p 基準のピクセル。",
	},
	countdown_opacity = {
		en = "Countdown: opacity",
		ru = "Отсчёт: непрозрачность",
		["zh-cn"] = "倒计时：不透明度",
		["zh-tw"] = "倒數：不透明度",
		ja = "カウントダウン：不透明度",
	},
	countdown_opacity_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	countdown_offset_x = {
		en = "Countdown: offset X",
		ru = "Отсчёт: смещение X",
		["zh-cn"] = "倒计时：X 偏移",
		["zh-tw"] = "倒數：X 偏移",
		ja = "カウントダウン：オフセット X",
	},
	countdown_offset_x_description = {
		en = "From the numbers' position. Positive is right.",
		ru = "От позиции чисел. Положительное -- вправо.",
		["zh-cn"] = "相对数字位置。正值向右。",
		["zh-tw"] = "相對數字位置。正值向右。",
		ja = "数字の位置が基準。正の値で右へ。",
	},
	countdown_offset_y = {
		en = "Countdown: offset Y",
		ru = "Отсчёт: смещение Y",
		["zh-cn"] = "倒计时：Y 偏移",
		["zh-tw"] = "倒數：Y 偏移",
		ja = "カウントダウン：オフセット Y",
	},
	countdown_offset_y_description = {
		en = "From the numbers' position. Positive is down.",
		ru = "От позиции чисел. Положительное -- вниз.",
		["zh-cn"] = "相对数字位置。正值向下。",
		["zh-tw"] = "相對數字位置。正值向下。",
		ja = "数字の位置が基準。正の値で下へ。",
	},

	color_mode = {
		en = "Colour",
		ru = "Цвет",
		["zh-cn"] = "颜色",
		["zh-tw"] = "顏色",
		ja = "色",
	},
	color_mode_description = {
		en = "One colour, or one per charge band.",
		ru = "Один цвет или свой на каждый диапазон зарядов.",
		["zh-cn"] = "单一颜色，或按充能区间各用一色。",
		["zh-tw"] = "單一顏色，或按充能區間各用一色。",
		ja = "単色、またはチャージ段階ごとに一色。",
	},
	color_mode_single = {
		en = "Single",
		ru = "Один",
		["zh-cn"] = "单色",
		["zh-tw"] = "單色",
		ja = "単色",
	},
	color_mode_thresholds = {
		en = "Per charge band",
		ru = "По диапазонам",
		["zh-cn"] = "按充能区间",
		["zh-tw"] = "按充能區間",
		ja = "段階ごと",
	},

	color_r = {
		en = "Colour: red",
		ru = "Цвет: красный",
		["zh-cn"] = "颜色：红",
		["zh-tw"] = "顏色：紅",
		ja = "色：赤",
	},
	color_r_description = {
		en = "0-255. In band mode: the colour above the bands.",
		ru = "0-255. В режиме диапазонов -- цвет выше диапазонов.",
		["zh-cn"] = "0-255。区间模式下为高于各区间时的颜色。",
		["zh-tw"] = "0-255。區間模式下為高於各區間時的顏色。",
		ja = "0-255。段階モードでは各段階より上の色。",
	},
	color_g = {
		en = "Colour: green",
		ru = "Цвет: зелёный",
		["zh-cn"] = "颜色：绿",
		["zh-tw"] = "顏色：綠",
		ja = "色：緑",
	},
	color_g_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	color_b = {
		en = "Colour: blue",
		ru = "Цвет: синий",
		["zh-cn"] = "颜色：蓝",
		["zh-tw"] = "顏色：藍",
		ja = "色：青",
	},
	color_b_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},

	low_max = {
		en = "Low band: up to",
		ru = "Нижний диапазон: до",
		["zh-cn"] = "低区间：上限",
		["zh-tw"] = "低區間：上限",
		ja = "低段階：上限",
	},
	low_max_description = {
		en = "Displayed number at or below this uses the low colour. Band mode only.",
		ru = "Показанное число не выше этого -- нижний цвет. Только в режиме диапазонов.",
		["zh-cn"] = "显示数字不高于此值时使用低区间颜色。仅限区间模式。",
		["zh-tw"] = "顯示數字不高於此值時使用低區間顏色。僅限區間模式。",
		ja = "表示中の数値がこれ以下なら低段階の色。段階モードのみ。",
	},
	low_r = {
		en = "Low band: red",
		ru = "Нижний диапазон: красный",
		["zh-cn"] = "低区间：红",
		["zh-tw"] = "低區間：紅",
		ja = "低段階：赤",
	},
	low_r_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	low_g = {
		en = "Low band: green",
		ru = "Нижний диапазон: зелёный",
		["zh-cn"] = "低区间：绿",
		["zh-tw"] = "低區間：綠",
		ja = "低段階：緑",
	},
	low_g_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	low_b = {
		en = "Low band: blue",
		ru = "Нижний диапазон: синий",
		["zh-cn"] = "低区间：蓝",
		["zh-tw"] = "低區間：藍",
		ja = "低段階：青",
	},
	low_b_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},

	mid_max = {
		en = "Middle band: up to",
		ru = "Средний диапазон: до",
		["zh-cn"] = "中区间：上限",
		["zh-tw"] = "中區間：上限",
		ja = "中段階：上限",
	},
	mid_max_description = {
		en = "Above the low band, at or below this. Band mode only.",
		ru = "Выше нижнего диапазона и не выше этого. Только в режиме диапазонов.",
		["zh-cn"] = "高于低区间且不高于此值。仅限区间模式。",
		["zh-tw"] = "高於低區間且不高於此值。僅限區間模式。",
		ja = "低段階より上でこれ以下。段階モードのみ。",
	},
	mid_r = {
		en = "Middle band: red",
		ru = "Средний диапазон: красный",
		["zh-cn"] = "中区间：红",
		["zh-tw"] = "中區間：紅",
		ja = "中段階：赤",
	},
	mid_r_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	mid_g = {
		en = "Middle band: green",
		ru = "Средний диапазон: зелёный",
		["zh-cn"] = "中区间：绿",
		["zh-tw"] = "中區間：綠",
		ja = "中段階：緑",
	},
	mid_g_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	mid_b = {
		en = "Middle band: blue",
		ru = "Средний диапазон: синий",
		["zh-cn"] = "中区间：蓝",
		["zh-tw"] = "中區間：藍",
		ja = "中段階：青",
	},
	mid_b_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},

	bar_enabled = {
		en = "Show the bar",
		ru = "Показывать полосу",
		["zh-cn"] = "显示进度条",
		["zh-tw"] = "顯示進度條",
		ja = "バーを表示",
	},
	bar_enabled_description = {
		en = "What it shows is picked below.",
		ru = "Что она показывает -- выбирается ниже.",
		["zh-cn"] = "显示内容在下方选择。",
		["zh-tw"] = "顯示內容在下方選擇。",
		ja = "表示内容は下で選択。",
	},

	bar_mode = {
		en = "The bar shows",
		ru = "Полоса показывает",
		["zh-cn"] = "进度条显示",
		["zh-tw"] = "進度條顯示",
		ja = "バーの表示内容",
	},
	bar_mode_description = {
		en = "Wind-up: visible while holding the special, stages marked on the bar. Recharge tick: time to the next charge.",
		ru = "Замах: видна, пока удерживается спецатака, стадии отмечены на полосе. Тик перезарядки: время до следующего заряда.",
		["zh-cn"] = "蓄力：按住特殊攻击时可见，阶段在条上标出。回充计时：距下一充能的时间。",
		["zh-tw"] = "蓄力：按住特殊攻擊時可見，階段在條上標出。回充計時：距下一充能的時間。",
		ja = "溜め：特殊攻撃を押している間だけ表示、段階をバー上に区切る。リチャージ：次のチャージまでの時間。",
	},
	bar_mode_windup = {
		en = "Special wind-up",
		ru = "Замах спецатаки",
		["zh-cn"] = "特殊攻击蓄力",
		["zh-tw"] = "特殊攻擊蓄力",
		ja = "特殊攻撃の溜め",
	},
	bar_mode_recharge = {
		en = "Recharge tick",
		ru = "Тик перезарядки",
		["zh-cn"] = "回充计时",
		["zh-tw"] = "回充計時",
		ja = "リチャージ",
	},

	bar_shape = {
		en = "Shape",
		ru = "Форма",
		["zh-cn"] = "形状",
		["zh-tw"] = "形狀",
		ja = "形状",
	},
	bar_shape_description = {
		en = "'One cell per charge' applies to the recharge tick; the wind-up bar splits at its stage boundaries instead. Past 12 charges the cells count special uses (Arc Maul: 8). Cells run horizontally.",
		ru = "«Ячейка на заряд» действует для тика перезарядки; полоса замаха делится по границам стадий. Свыше 12 зарядов ячейки считают применения (дуговая булава: 8). Ячейки всегда горизонтальны.",
		["zh-cn"] = "「每充能一格」仅用于回充计时；蓄力条按阶段边界分段。充能超过 12 时，格子改为按使用次数计（电弧锤：8 格）。格子始终水平排列。",
		["zh-tw"] = "「每充能一格」僅用於回充計時；蓄力條按階段邊界分段。充能超過 12 時，格子改為按使用次數計（電弧鎚：8 格）。格子始終水平排列。",
		ja = "「1チャージ1マス」はリチャージ表示用。溜めバーは段階の境界で区切る。チャージが 12 を超えると使用回数でマスを数える（アークモール：8）。マスは常に横並び。",
	},
	bar_shape_horizontal = {
		en = "Horizontal",
		ru = "Горизонтальная",
		["zh-cn"] = "水平",
		["zh-tw"] = "水平",
		ja = "横",
	},
	bar_shape_vertical = {
		en = "Vertical",
		ru = "Вертикальная",
		["zh-cn"] = "垂直",
		["zh-tw"] = "垂直",
		ja = "縦",
	},
	bar_shape_segments = {
		en = "One cell per charge",
		ru = "Ячейка на заряд",
		["zh-cn"] = "每充能一格",
		["zh-tw"] = "每充能一格",
		ja = "1チャージ1マス",
	},

	bar_length = {
		en = "Length",
		ru = "Длина",
		["zh-cn"] = "长度",
		["zh-tw"] = "長度",
		ja = "長さ",
	},
	bar_length_description = {
		en = "1080p reference pixels. 200 = stamina/dodge bar width.",
		ru = "Пиксели при 1080p. 200 = ширина полос выносливости/уклонения.",
		["zh-cn"] = "以 1080p 为基准的像素。200 = 耐力/闪避条的宽度。",
		["zh-tw"] = "以 1080p 為基準的像素。200 = 耐力/閃避條的寬度。",
		ja = "1080p 基準のピクセル。200 = スタミナ／回避バーの幅。",
	},
	bar_thickness = {
		en = "Thickness",
		ru = "Толщина",
		["zh-cn"] = "粗细",
		["zh-tw"] = "粗細",
		ja = "太さ",
	},
	bar_thickness_description = {
		en = "1080p reference pixels.",
		ru = "Пиксели при 1080p.",
		["zh-cn"] = "以 1080p 为基准的像素。",
		["zh-tw"] = "以 1080p 為基準的像素。",
		ja = "1080p 基準のピクセル。",
	},

	bar_offset_x = {
		en = "Offset X",
		ru = "Смещение X",
		["zh-cn"] = "X 偏移",
		["zh-tw"] = "X 偏移",
		ja = "オフセット X",
	},
	bar_offset_x_description = {
		en = "Positive is right. Custom HUD users: drag the element instead.",
		ru = "Положительное -- вправо. С Custom HUD лучше перетащить элемент.",
		["zh-cn"] = "正值向右。Custom HUD 用户：请直接拖动元素。",
		["zh-tw"] = "正值向右。Custom HUD 使用者：請直接拖曳元件。",
		ja = "正の値で右へ。Custom HUD 使用時は要素をドラッグ推奨。",
	},
	bar_offset_y = {
		en = "Offset Y",
		ru = "Смещение Y",
		["zh-cn"] = "Y 偏移",
		["zh-tw"] = "Y 偏移",
		ja = "オフセット Y",
	},
	bar_offset_y_description = {
		en = "Positive is down. 248 = just under the dodge bar.",
		ru = "Положительное -- вниз. 248 = сразу под полосой уклонения.",
		["zh-cn"] = "正值向下。248 = 紧贴闪避条下方。",
		["zh-tw"] = "正值向下。248 = 緊貼閃避條下方。",
		ja = "正の値で下へ。248 = 回避バーのすぐ下。",
	},

	bar_opacity = {
		en = "Opacity",
		ru = "Непрозрачность",
		["zh-cn"] = "不透明度",
		["zh-tw"] = "不透明度",
		ja = "不透明度",
	},
	bar_opacity_description = {
		en = "Fill alpha, 0-255.",
		ru = "Альфа заливки, 0-255.",
		["zh-cn"] = "填充透明度，0-255。",
		["zh-tw"] = "填滿透明度，0-255。",
		ja = "塗りのアルファ、0-255。",
	},

	bar_hide_at_max = {
		en = "Hide at full charges",
		ru = "Скрывать при полном запасе",
		["zh-cn"] = "充能满时隐藏",
		["zh-tw"] = "充能滿時隱藏",
		ja = "満タン時に隠す",
	},
	bar_hide_at_max_description = {
		en = "Recharge tick only.",
		ru = "Только для тика перезарядки.",
		["zh-cn"] = "仅限回充计时。",
		["zh-tw"] = "僅限回充計時。",
		ja = "リチャージ表示のみ。",
	},

	regen_r = {
		en = "Fill: red",
		ru = "Заливка: красный",
		["zh-cn"] = "填充：红",
		["zh-tw"] = "填滿：紅",
		ja = "塗り：赤",
	},
	regen_r_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	regen_g = {
		en = "Fill: green",
		ru = "Заливка: зелёный",
		["zh-cn"] = "填充：绿",
		["zh-tw"] = "填滿：綠",
		ja = "塗り：緑",
	},
	regen_g_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	regen_b = {
		en = "Fill: blue",
		ru = "Заливка: синий",
		["zh-cn"] = "填充：蓝",
		["zh-tw"] = "填滿：藍",
		ja = "塗り：青",
	},
	regen_b_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},

	retention_r = {
		en = "Final stage: red",
		ru = "Финальная стадия: красный",
		["zh-cn"] = "最终阶段：红",
		["zh-tw"] = "最終階段：紅",
		ja = "最終段階：赤",
	},
	retention_r_description = {
		en = "Wind-up bar's last stage: heavy at full effect, auto-release coming. 0-255.",
		ru = "Последняя стадия полосы замаха: тяжёлая атака в полную силу, скоро автоспуск. 0-255.",
		["zh-cn"] = "蓄力条的最后阶段：重攻击已达全额效果，即将自动释放。0-255。",
		["zh-tw"] = "蓄力條的最後階段：重攻擊已達全額效果，即將自動釋放。0-255。",
		ja = "溜めバーの最終段階：強攻撃が最大効果、まもなく自動リリース。0-255。",
	},
	retention_g = {
		en = "Final stage: green",
		ru = "Финальная стадия: зелёный",
		["zh-cn"] = "最终阶段：绿",
		["zh-tw"] = "最終階段：綠",
		ja = "最終段階：緑",
	},
	retention_g_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	retention_b = {
		en = "Final stage: blue",
		ru = "Финальная стадия: синий",
		["zh-cn"] = "最终阶段：蓝",
		["zh-tw"] = "最終階段：藍",
		ja = "最終段階：青",
	},
	retention_b_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},

	track_r = {
		en = "Background: red",
		ru = "Фон: красный",
		["zh-cn"] = "背景：红",
		["zh-tw"] = "背景：紅",
		ja = "背景：赤",
	},
	track_r_description = {
		en = "0-255. Also the underline's background.",
		ru = "0-255. Также фон подчёркивания.",
		["zh-cn"] = "0-255。也是下划线的背景。",
		["zh-tw"] = "0-255。也是底線的背景。",
		ja = "0-255。下線の背景も兼ねる。",
	},
	track_g = {
		en = "Background: green",
		ru = "Фон: зелёный",
		["zh-cn"] = "背景：绿",
		["zh-tw"] = "背景：綠",
		ja = "背景：緑",
	},
	track_g_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	track_b = {
		en = "Background: blue",
		ru = "Фон: синий",
		["zh-cn"] = "背景：蓝",
		["zh-tw"] = "背景：藍",
		ja = "背景：青",
	},
	track_b_description = {
		en = "0-255.",
		ru = "0-255.",
		["zh-cn"] = "0-255。",
		["zh-tw"] = "0-255。",
		ja = "0-255。",
	},
	track_opacity = {
		en = "Background opacity",
		ru = "Непрозрачность фона",
		["zh-cn"] = "背景不透明度",
		["zh-tw"] = "背景不透明度",
		ja = "背景の不透明度",
	},
	track_opacity_description = {
		en = "0-255. 0 = fill only.",
		ru = "0-255. 0 = только заливка.",
		["zh-cn"] = "0-255。0 = 仅显示填充。",
		["zh-tw"] = "0-255。0 = 僅顯示填滿。",
		ja = "0-255。0 = 塗りのみ。",
	},

	stock_gauge = {
		en = "Stock gauge",
		ru = "Штатная шкала",
		["zh-cn"] = "原版充能表",
		["zh-tw"] = "原版充能表",
		ja = "標準ゲージ",
	},
	stock_gauge_description = {
		en = "The game's own charge arc for covered weapons.",
		ru = "Игровая дуга зарядов у охваченного оружия.",
		["zh-cn"] = "游戏自带的充能弧（针对覆盖的武器）。",
		["zh-tw"] = "遊戲自帶的充能弧（針對覆蓋的武器）。",
		ja = "ゲーム本来のチャージ弧（対象武器のみ）。",
	},
	stock_gauge_hidden = {
		en = "Hidden",
		ru = "Скрыта",
		["zh-cn"] = "隐藏",
		["zh-tw"] = "隱藏",
		ja = "非表示",
	},
	stock_gauge_original = {
		en = "Untouched",
		ru = "Как есть",
		["zh-cn"] = "保持原样",
		["zh-tw"] = "保持原樣",
		ja = "そのまま",
	},
	stock_gauge_transformed = {
		en = "Turned / moved",
		ru = "Повёрнута / сдвинута",
		["zh-cn"] = "旋转 / 移动",
		["zh-tw"] = "旋轉 / 移動",
		ja = "回転／移動",
	},

	stock_rotation = {
		en = "Rotation",
		ru = "Поворот",
		["zh-cn"] = "旋转",
		["zh-tw"] = "旋轉",
		ja = "回転",
	},
	stock_rotation_description = {
		en = "Degrees. 90 or -90 swings the arc above or below the reticle; it turns, it cannot straighten. 'Turned / moved' only.",
		ru = "Градусы. 90 или -90 уводит дугу над прицел или под него; она поворачивается, но не распрямляется. Только для «Повёрнута / сдвинута».",
		["zh-cn"] = "角度。90 或 -90 会把弧线转到准星上方或下方；它只能旋转，不能拉直。仅限「旋转 / 移动」。",
		["zh-tw"] = "角度。90 或 -90 會把弧線轉到準星上方或下方；它只能旋轉，不能拉直。僅限「旋轉 / 移動」。",
		ja = "度数。90 か -90 で弧をレティクルの上か下へ。回転のみで、直線にはならない。「回転／移動」時のみ。",
	},
	stock_offset_x = {
		en = "Offset X",
		ru = "Смещение X",
		["zh-cn"] = "X 偏移",
		["zh-tw"] = "X 偏移",
		ja = "オフセット X",
	},
	stock_offset_x_description = {
		en = "On top of the reticle anchor. 'Turned / moved' only.",
		ru = "Поверх привязки к прицелу. Только для «Повёрнута / сдвинута».",
		["zh-cn"] = "叠加在准星锚点上。仅限「旋转 / 移动」。",
		["zh-tw"] = "疊加在準星錨點上。僅限「旋轉 / 移動」。",
		ja = "レティクルのアンカーに加算。「回転／移動」時のみ。",
	},
	stock_offset_y = {
		en = "Offset Y",
		ru = "Смещение Y",
		["zh-cn"] = "Y 偏移",
		["zh-tw"] = "Y 偏移",
		ja = "オフセット Y",
	},
	stock_offset_y_description = {
		en = "Positive is down. 'Turned / moved' only.",
		ru = "Положительное -- вниз. Только для «Повёрнута / сдвинута».",
		["zh-cn"] = "正值向下。仅限「旋转 / 移动」。",
		["zh-tw"] = "正值向下。僅限「旋轉 / 移動」。",
		ja = "正の値で下へ。「回転／移動」時のみ。",
	},

	stock_mirror = {
		en = "Mirror",
		ru = "Отражение",
		["zh-cn"] = "镜像",
		["zh-tw"] = "鏡像",
		ja = "反転",
	},
	stock_mirror_description = {
		en = "Flips the arc's opening to the other side. 'Turned / moved' only.",
		ru = "Разворачивает раскрытие дуги в другую сторону. Только для «Повёрнута / сдвинута».",
		["zh-cn"] = "把弧口翻到另一侧。仅限「旋转 / 移动」。",
		["zh-tw"] = "把弧口翻到另一側。僅限「旋轉 / 移動」。",
		ja = "弧の開きを反対側へ。「回転／移動」時のみ。",
	},
	stock_mirror_none = {
		en = "None",
		ru = "Нет",
		["zh-cn"] = "无",
		["zh-tw"] = "無",
		ja = "なし",
	},
	stock_mirror_horizontal = {
		en = "Horizontal",
		ru = "По горизонтали",
		["zh-cn"] = "水平",
		["zh-tw"] = "水平",
		ja = "水平",
	},
	stock_mirror_vertical = {
		en = "Vertical",
		ru = "По вертикали",
		["zh-cn"] = "垂直",
		["zh-tw"] = "垂直",
		ja = "垂直",
	},
	stock_mirror_both = {
		en = "Both",
		ru = "Оба",
		["zh-cn"] = "两者",
		["zh-tw"] = "兩者",
		ja = "両方",
	},

	stock_recolor = {
		en = "Recolour",
		ru = "Перекрасить",
		["zh-cn"] = "重新着色",
		["zh-tw"] = "重新著色",
		ja = "色を変更",
	},
	stock_recolor_description = {
		en = "Repaint the stock gauge's segments. Starts on the game's own colours - nothing changes until a slider moves. Ignored while the gauge is hidden.",
		ru = "Перекрашивает сегменты штатной шкалы. Начинает с игровых цветов - пока не сдвинешь ползунок, ничего не изменится. Со скрытой шкалой не работает.",
		["zh-cn"] = "重新着色原版充能表的分段。初始值即游戏原色 - 不动滑块就没有变化。充能表隐藏时无效。",
		["zh-tw"] = "重新著色原版充能表的分段。初始值即遊戲原色 - 不動滑桿就沒有變化。充能表隱藏時無效。",
		ja = "標準ゲージのセグメントを塗り替える。初期値はゲーム本来の色 - スライダーを動かすまで変化なし。ゲージ非表示時は無効。",
	},
	stock_filled_r = {
		en = "Charged: red",
		ru = "Заряжено: красный",
		["zh-cn"] = "已充能：红",
		["zh-tw"] = "已充能：紅",
		ja = "充填済み：赤",
	},
	stock_filled_r_description = {
		en = "0-255. Segments that still hold a charge. Game default 216.",
		ru = "0-255. Сегменты с зарядом. В игре по умолчанию 216.",
		["zh-cn"] = "0-255。仍有充能的分段。游戏默认 216。",
		["zh-tw"] = "0-255。仍有充能的分段。遊戲預設 216。",
		ja = "0-255。チャージが残るセグメント。ゲーム既定値は 216。",
	},
	stock_filled_g = {
		en = "Charged: green",
		ru = "Заряжено: зелёный",
		["zh-cn"] = "已充能：绿",
		["zh-tw"] = "已充能：綠",
		ja = "充填済み：緑",
	},
	stock_filled_g_description = {
		en = "0-255. Segments that still hold a charge. Game default 229.",
		ru = "0-255. Сегменты с зарядом. В игре по умолчанию 229.",
		["zh-cn"] = "0-255。仍有充能的分段。游戏默认 229。",
		["zh-tw"] = "0-255。仍有充能的分段。遊戲預設 229。",
		ja = "0-255。チャージが残るセグメント。ゲーム既定値は 229。",
	},
	stock_filled_b = {
		en = "Charged: blue",
		ru = "Заряжено: синий",
		["zh-cn"] = "已充能：蓝",
		["zh-tw"] = "已充能：藍",
		ja = "充填済み：青",
	},
	stock_filled_b_description = {
		en = "0-255. Segments that still hold a charge. Game default 207.",
		ru = "0-255. Сегменты с зарядом. В игре по умолчанию 207.",
		["zh-cn"] = "0-255。仍有充能的分段。游戏默认 207。",
		["zh-tw"] = "0-255。仍有充能的分段。遊戲預設 207。",
		ja = "0-255。チャージが残るセグメント。ゲーム既定値は 207。",
	},
	stock_unfilled_r = {
		en = "Spent: red",
		ru = "Потрачено: красный",
		["zh-cn"] = "未充能：红",
		["zh-tw"] = "未充能：紅",
		ja = "未充填：赤",
	},
	stock_unfilled_r_description = {
		en = "0-255. Segments already spent. Game default 169.",
		ru = "0-255. Уже потраченные сегменты. В игре по умолчанию 169.",
		["zh-cn"] = "0-255。已消耗的分段。游戏默认 169。",
		["zh-tw"] = "0-255。已消耗的分段。遊戲預設 169。",
		ja = "0-255。消費済みのセグメント。ゲーム既定値は 169。",
	},
	stock_unfilled_g = {
		en = "Spent: green",
		ru = "Потрачено: зелёный",
		["zh-cn"] = "未充能：绿",
		["zh-tw"] = "未充能：綠",
		ja = "未充填：緑",
	},
	stock_unfilled_g_description = {
		en = "0-255. Segments already spent. Game default 191.",
		ru = "0-255. Уже потраченные сегменты. В игре по умолчанию 191.",
		["zh-cn"] = "0-255。已消耗的分段。游戏默认 191。",
		["zh-tw"] = "0-255。已消耗的分段。遊戲預設 191。",
		ja = "0-255。消費済みのセグメント。ゲーム既定値は 191。",
	},
	stock_unfilled_b = {
		en = "Spent: blue",
		ru = "Потрачено: синий",
		["zh-cn"] = "未充能：蓝",
		["zh-tw"] = "未充能：藍",
		ja = "未充填：青",
	},
	stock_unfilled_b_description = {
		en = "0-255. Segments already spent. Game default 153.",
		ru = "0-255. Уже потраченные сегменты. В игре по умолчанию 153.",
		["zh-cn"] = "0-255。已消耗的分段。游戏默认 153。",
		["zh-tw"] = "0-255。已消耗的分段。遊戲預設 153。",
		ja = "0-255。消費済みのセグメント。ゲーム既定値は 153。",
	},

	show_when_stowed = {
		en = "Show while stowed",
		ru = "Показывать с убранным оружием",
		["zh-cn"] = "收起时仍显示",
		["zh-tw"] = "收起時仍顯示",
		ja = "収納中も表示",
	},
	show_when_stowed_description = {
		en = "Keep the numbers and recharge readouts up while another weapon is wielded.",
		ru = "Числа и индикация перезарядки видны, пока в руках другое оружие.",
		["zh-cn"] = "手持其他武器时，仍显示数字与回充读数。",
		["zh-tw"] = "手持其他武器時，仍顯示數字與回充讀數。",
		ja = "別の武器を持っている間も数字とリチャージ表示を出す。",
	},

	scope = {
		en = "Weapons covered",
		ru = "Охват оружия",
		["zh-cn"] = "覆盖武器",
		["zh-tw"] = "覆蓋武器",
		ja = "対象武器",
	},
	scope_description = {
		en = "Cooldown only = Mechanicus Power Sword and Arc Maul. All adds kill/block charges, e.g. the two-handed force sword.",
		ru = "Только кулдаун = силовой меч Механикус и дуговая булава. «Все» добавляет заряды за убийства/блоки, например двуручный психосиловой меч.",
		["zh-cn"] = "仅冷却 = 机械教动力剑和电弧锤。「全部」加入击杀/格挡充能武器，例如双手灵能剑。",
		["zh-tw"] = "僅冷卻 = 機械教動力劍和電弧鎚。「全部」加入擊殺/格擋充能武器，例如雙手靈能劍。",
		ja = "クールダウンのみ = メカニカス・パワーソードとアークモール。「すべて」はキル／ブロック式も対象、例：両手持ちフォースソード。",
	},
	scope_all_charges = {
		en = "All charge weapons",
		ru = "Всё зарядное оружие",
		["zh-cn"] = "全部充能武器",
		["zh-tw"] = "全部充能武器",
		ja = "すべてのチャージ武器",
	},
	scope_cooldown_only = {
		en = "Cooldown charges only",
		ru = "Только заряды по кулдауну",
		["zh-cn"] = "仅冷却充能",
		["zh-tw"] = "僅冷卻充能",
		ja = "クールダウン式のみ",
	},
}
